### ISSUE TITLE
Issues after initial design review

### ISSUE THREAD

**Issue by oftfrfbf** [mira67/mira67.github.io#1]
[ FIRST PAGE ]
1. Display "Results" on 1st page
2. Directly Display "Result" without user configuration
3. Region Selection Option
4. Fine Grained Map {Ice, Water, Topography}
5. User Configuration Panel
     a - memorize selections
     b - date bar
     c - display "selections"
6. Progress Bar "waiting for results"
7. Abbreviate lat/lon "37.6" 

[ SECOND PAGE ]
1. Highlight "Region and Anomalies"
2. Zoom in/out on selected region
3. Side by side result comparison
4. Results temporal zoom-in "ref to fira??? g???..." <--- couldn't read this one?
5. The Hz with 2nd page
6. Background "simpler"
![2015-10-07 16 38 03](https://cloud.githubusercontent.com/assets/7818564/10395113/7c1592a6-6e58-11e5-8a73-3ea2fa35c51a.jpg)
![2015-10-07 16 38 07](https://cloud.githubusercontent.com/assets/7818564/10395116/7df6272a-6e58-11e5-9f06-a061bcc0b451.jpg)

**Comment by mira67** [comment]
Separate the issue in to different issue, one by one, such that after one is done, we can close it. Thanks!
