### ISSUE TITLE
Region selection with editing boxes

### ISSUE THREAD

**Issue by mira67** [mira67/mira67.github.io#5]
Allow user to adjust the region with coordinations input

**Comment by mira67** [comment]
For the region editing boxes, currently, you use N/S/W/E, this needs to be changed to lat/lon location for each corner of the region rectangle, right?

**Comment by oftfrfbf** [comment]
What I have implemented uses a latitude for each of the North and South,
and then a longitude for each of the East and West.

**Comment by mira67** [comment]
I see, we assume that bound a rectangle, right? thanks for the clarification.

**Comment by oftfrfbf** [comment]
Yes.
